<a href="https://colab.research.google.com/github/suhongkim98/study-machine-learning/blob/main/_NumPy_%ED%95%9C%EB%B2%88%EC%97%90_%EC%A0%9C%EB%8C%80%EB%A1%9C_%EB%B0%B0%EC%9A%B0%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy 한번에 제대로 배우기
* https://youtu.be/mirZPrWwvao 유튜브를 보며 공부한 내용이다.
* NumPy 최신 업데이트 관련 Docs는 https://numpy.org/ 에서 확인하자



---



## NumPy 특징

1.   항목 추가
2.   항목 추가



* Numerical Python의 약자
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅(broadcasting) 기능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
* 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [ ]:
import numpy as np
np.__version__

'1.19.5'



---



## 배열 생성

### 리스트로 배열 만들기


In [ ]:
a1 = np.array([1, 2, 3, 4, 5]) # 리스트를 이용해 1차원의 np 배열 생성
print(a1)
print(type(a1))
print(a1.shape) # 5개의 갯수를 가진 1차원 배열
# 우리가 리스트 사용하듯 접근, 수정이 가능하다.
print(a1[0], a1[1], a1[2], a1[3])
a1[0] = 4
a1[1] = 5
print(a1[0])

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4
4


In [ ]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]]) # 2차원 배열 생성
print(a2)
print(a2.shape)
#2개의 인덱스로 접근 및 수정이 가능 하다
print(a2[0,0], a2[1,1], a2[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3) aab
1 5 9


In [ ]:
a3 = np.array([
    [ [1,2,3],[4,5,6],[7,8,9] ],
    [ [1,2,3],[4,5,6],[7,8,9] ],
    [ [1,2,3],[4,5,6],[7,8,9] ],
     ]) #3차원 배열 생성

print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


### 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [ ]:
np.zeros(10) # 10개의 요소를 0으로 초기화

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `ones()`: 모든 요소를 1로 초기화

In [ ]:
np.ones(10) # 10개의 요소를 1로 초기화

np.ones((3,3)) # shape모양을 이용해 배열 초기화도 가능하다.

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* `full()`: 모든 요소를 지정한 값으로 초기화

In [ ]:
np.full((3,3), 1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [ ]:
 # 단위행렬은 주 대각선이 1이고 나머지는 0인 정사각형 형태의 특징을 가지고 있다.
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* `tri()`: 삼각행렬 생성

In [ ]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [ ]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [ ]:
print(a1)
np.zeros_like(a1) # a1과 shape가 같은 0으로 초기화한 배열을 만들어 줭

[4 5 3 4 5]


array([0, 0, 0, 0, 0])

In [ ]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
print(a3)
np.full_like(a3, 10) # a3과 shape가 같은 10으로 초기화한 배열을 만들어 줭

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

### 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [ ]:
# python의 range함수를 그대로 배열에 생성하는데 활용한다고 생각해라

np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

* `linspace()`: 범위 내에서 균등 간격의 배열 생성

In [ ]:
np.linspace(0, 1, 5) # 0부터 1까지 균등한 간격으로 5개 원소를 생성해줘

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

* `logspace()`: 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [ ]:
np.logspace(0.1, 1, 20) # log scale 단위로 균등하게

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

### 랜덤값으로 배열 생성


* `random.random()`: 랜덤한 수의 배열 생성

In [ ]:
# 파이썬의 랜덤과 유사하다
np.random.random((3,3))

array([[0.02993888, 0.5360059 , 0.73264415],
       [0.77407229, 0.72839323, 0.29063108],
       [0.73207045, 0.18683186, 0.52947586]])

* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [ ]:
np.random.randint(0, 10, (3,3)) # 0부터 9까지 3,3shape형태로 배열 생성

array([[2, 1, 9],
       [1, 6, 5],
       [8, 7, 8]])

* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [ ]:
np.random.normal(0,1,(3,3))

array([[-1.10495923, -0.8925578 , -0.51288732],
       [ 0.67210622, -0.66430756, -0.75135838],
       [ 1.09708199,  1.25929788,  0.00572812]])

* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [ ]:
np.random.rand(3,3)

array([[0.59937817, 0.04061949, 0.07908881],
       [0.79488907, 0.68564658, 0.48928495],
       [0.48064495, 0.9632426 , 0.93116224]])

* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [ ]:
np.random.randn(3,3)

array([[-6.19934997e-01,  5.13566761e-04, -4.31937786e-01],
       [-6.08178886e-01,  2.51142393e-01,  7.38900968e-03],
       [-6.01961610e-01,  2.57530064e-01, -1.40397706e+00]])

### 표준 데이터 타입

numpy만의 자료형이 존재한다.<br/>
dtype을 주어서 사용

In [ ]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3,3), dtype=bool) # 1은 True를 의미

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.full((3,3), 1.0, dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 날짜/시간 배열 생성


In [ ]:
# 문자열로 나타내도 dtype을 날짜로 주면 날짜로 인식한다
date = np.array('2020-01-01', dtype=np.datetime64) 
date

array('2020-01-01', dtype='datetime64[D]')

In [ ]:
# 이렇게 date를 계산할 수 있다
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [ ]:
datetime = np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [ ]:
datetime = np.datetime64('2020-06-01 12:00:12.34', 'ns') # 나노초까지 ns를 주고 .으로 표현가능
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')



---



## 배열 조회

### 배열 속성 정보

In [ ]:
def array_info(array):
  print(array)
  print('ndim:', array.ndim) # dimension의 갯수
  print('shape:', array.shape)
  print('dtype:', array.dtype)
  print('size:', array.size)
  print('itemsize:', array.itemsize) # 하나의 아이템이 가지고 있는 바이트 사이즈
  print('nbytes:',array.nbytes) # array의 전체크기 byte단위
  print('strides:',array.strides) # 다음 차원으로 넘어갈 때 얼마나 필요한가

In [ ]:
array_info(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: int64
size: 9
itemsize: 8
nbytes: 72
strides: (24, 8)


In [ ]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: int64
size: 9
itemsize: 8
nbytes: 72
strides: (24, 8)


In [ ]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim: 3
shape: (3, 3, 3)
dtype: int64
size: 27
itemsize: 8
nbytes: 216
strides: (72, 24, 8)


### 인덱싱(Indexing)

In [ ]:
print(a1)
print(a1[0])
print(a1[1])
print(a1[-1]) # 파이썬 리스트와 마찬가지로 음수로도 접근가능

[4 5 3 4 5]
4
5
5


In [ ]:
print(a2)
print(a2[0,0])
print(a2[0,2])
print(a2[-1,1]) # 파이썬 리스트와 마찬가지로 음수로도 접근가능

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
8


In [ ]:
print(a3)
print(a3[0,0,0])
print(a3[1,1,1])
print(a3[-1,1,-2])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
5


### 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [ ]:
#파이썬 리스트와 마찬가지로 슬라이싱 가능
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[::2])
print(a1[::-1])

[4 5 3 4 5]
[4 5]
[4 5 3 4 5]
[4 3 5]
[5 4 3 5 4]


In [ ]:
print(a2)
print(a2[1])
print(a2[1, :])
print(a2[:2, :2])
print(a2[1:,::-1])
print(a2[::-1,::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [ ]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi]) # index 대신에 boolean index를 넣어서 요소선택 가능
bi = [True,False,True,True,False]
print(a1[bi])

[4 5 3 4 5]
[5 3 5]
[4 3 4]


In [ ]:
print(a2)
bi = np.random.randint(0,2,(3,3), dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ True False  True]
 [False False False]
 [False False  True]]
[1 3 9]


### 팬시 인덱싱(Fancy Indedxing)

In [ ]:
print(a1)
print([a1[0], a1[2]])
ind = [0,2]
print(a1[ind])

# 1차원 배열에 2차원 배열 인덱스를 넣어주면 2차원 배열로 만들어준다
ind = np.array([
                [0,1],
                [2,0],
])
print(a1[ind])

[4 5 3 4 5]
[4, 3]
[4 3]
[[4 5]
 [3 4]]


In [ ]:
print(a2)
row = np.array([0,2])
col = np.array([1,2])
print(a2[row,col])

#슬라이싱 등 혼합해서 사용 가능
print(a2[row, :])
print(a2[:, col])
print(a2[1:, col])
print(a2[row, 1:])
print(a2[1:, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[[5 6]
 [8 9]]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]




---



## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [117]:
print(a1)
b1 = np.insert(a1, 0, 10) # a1의 0번째 위치에 10을 넣어서 배열을 새로 생성해줘
print(b1)
print(a1) # a1은 바뀌지 않음

c1 = np.insert(a1, 2, 10)
print(c1)

[4 5 3 4 5]
[10  4  5  3  4  5]
[4 5 3 4 5]
[ 4  5 10  3  4  5]


In [120]:
print(a2)

# 2차원 배열이기에 axis(축) 지정 가능
b2 = np.insert(a2, 1, 10, axis=0) 
print(b2)

c2 = np.insert(a2, 1, 10, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[10 10  1  2  3  4  5  6  7  8  9]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

In [126]:
print(a1)

a1[0] = 1
a1[1] = 2
a1[2] = 3
print(a1)

a1[:1] = 9
print(a1)

i = np.array([1,3,4])
a1[i] = 0 # 1,3,4인덱스를 0으로 바꾼다
print(a1)

a1[i] += 4
print(a1)

[9 0 3 0 0]
[1 2 3 0 0]
[9 2 3 0 0]
[9 0 3 0 0]
[9 4 3 4 4]


In [127]:
print(a2)
a2[0,0] = 1
a2[1,1] = 2
print(a2)

a2[0] = 1 # 첫번째 row를 다 1로 바꾼다
print(a2)

row = np.array([0,1]) # fancy indexing
col = np.array([1,2])
a2[row,col] = 0
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 2 6]
 [7 8 9]]
[[1 1 1]
 [4 2 6]
 [7 8 9]]


### 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* **원본 배열 변경없이 새로운 배열 반환**

In [128]:
print(a1)
b1 = np.delete(a1, 1) # 원본 배열은 바뀌지 않는다
print(b1) 

[9 4 3 4 4]
[9 3 4 4]


In [130]:
print(a2)

b2 = np.delete(a2, 1, axis=0)
print(b2)

c2 = np.delete(a2, 1, axis=1)
print(c2)

[[1 1 1]
 [4 2 6]
 [7 8 9]]
[[1 1 1]
 [7 8 9]]
[[1 1]
 [4 6]
 [7 9]]


### 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

파이썬 리스트는 슬라이스하면 복사본을 가져오는데 numpy배열은 그렇지 않아 변화가 발생할 경우 원본에 영향을 준다.

In [135]:
print(a2)
print(a2[:2,:2])

a2_sub = a2[:2, :2]
print(a2_sub)

a2_sub[:, 1] = 0
print(a2_sub)

print(a2) # a2_sub에 변화를 주었는데 원본데이터도 변경되었다

[[1 0 1]
 [4 0 6]
 [7 8 9]]
[[1 0]
 [4 0]]
[[1 0]
 [4 0]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 6]
 [7 8 9]]



* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [138]:
# 복사하고 싶으면 copy()를 붙여줘야한다
print(a2)
a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy)
a2_sub_copy[:, 1] = 1

print(a2) # 복사본을 변경한 것이므로 원본은 변화x

[[1 0 1]
 [4 0 6]
 [7 8 9]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 6]
 [7 8 9]]




---



## 배열 변환

### 배열 전치 및 축 변경

In [139]:
print(a2)
print(a2.T) # .T를 붙이면 전치가 된다

[[1 0 1]
 [4 0 6]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 6 9]]


In [140]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [145]:
print(a2)
print(a2.swapaxes(1,0)) # 1과 0축을 스왑한다

[[1 0 1]
 [4 0 6]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 6 9]]


In [146]:
print(a3)
print(a3.swapaxes(0,1)) # 0과 1축을 스왑한다
print(a3.swapaxes(1,2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


### 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [151]:
n1 = np.arange(1,10)
print(n1)

print(n1.reshape(3,3)) # 1차원을 3차원으로 변경

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* `newaxis()`: 새로운 축 추가

In [155]:
print(n1)
print(n1[np.newaxis, :5])
print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경

* 배열 모양만 변경

In [157]:
n2 = np.random.randint(0, 10, (2,5))
print(n2)

n2.resize((5,2))
print(n2)

[[6 4 2 0 9]
 [5 9 4 7 5]]
[[6 4]
 [2 0]
 [9 5]
 [9 4]
 [7 5]]


* 배열 크기 증가
* 남은 공간은 0으로 채워짐

In [158]:
n2.resize((5,5))
print(n2)

[[6 4 2 0 9]
 [5 9 4 7 5]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


* 배열 크기 감소
* 포함되지 않은 값은 삭제됨

In [159]:
n2.resize((3,3))
print(n2)

[[6 4 2]
 [0 9 5]
 [9 4 7]]


### 배열 추가

* `append()`: 배열의 끝에 값 추가

In [160]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)

b2 = np.arange(10, 19).reshape(3,3)
print(b2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [161]:
c2 = np.append(a2, b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


* axis를 0으로 지정
* shape[0]을 제외한 나머지 shape은 같아야 함

In [162]:
c2 = np.append(a2, b2, axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


* axis를 1로 지정
* shape[1]을 제외한 나머지 shape은 같아야 함

In [163]:
c2 = np.append(a2, b2, axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결

* `concatenate()`: 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [164]:
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1,b1])

array([1, 3, 5, 2, 4, 6])

In [165]:
c1 = np.array([7,8,9])
np.concatenate([a1,b1,c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [167]:
a2 = np.array([[1,2,3],
               [4,5,6]])
np.concatenate([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [168]:
a2 = np.array([[1,2,3],
               [4,5,6]])
np.concatenate([a2, a2], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `vstack()`: 수직 스택(vertical stack), 1차원으로 연결

In [169]:
np.vstack([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* `hstack()`: 수평 스택(horizontal stack), 2차원으로 연결

In [170]:
np.hstack([a2,a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `dstack()`: 깊이 스택(depth stack), 3차원으로 연결

In [171]:
np.dstack([a2,a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

* `stack()`: 새로운 차원으로 연결

In [172]:
np.stack([a2,a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### 배열 분할

* `split()`: 배열 분할

In [176]:
a1 = np.arange(0,10)
print(a1)

#기준 인덱스에 따라 스플릿 가능
b1, c1 = np.split(a1, [5])
print(b1,c1)

b1, c1, d1, e1, f1 = np.split(a1, [2,4,6,8])
print(b1,c1,d1,e1,f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


* `vsplit()`: 수직 분할, 1차원으로 분할

In [178]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2, c2 = np.vsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


* `hsplit()`: 수평 분할, 2차원으로 분할

In [179]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2, c2 = np.hsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


* `dsplit()`: 깊이 분할, 3차원으로 분할

In [182]:
a3 = np.arange(1,28).reshape(3,3,3)
print(a3)

b3, c3 = np.dsplit(a3, [2])
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]




---



## 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

* shape이 다르면 맞추고 연산을 해준다

In [191]:
a1 = np.array([1,2,3])
print(a1)

print(a1 + 5)

[1 2 3]
[6 7 8]


In [194]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
print(a1+a2)

b2 = np.array([1,2,3]).reshape(3,1)
print(b2)
print(a1 + b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


### 산술 연산(Arithmetic Operators)

In [207]:
a1 = np.arange(1,10)
print(a1)
# a1 + 1처럼 연산자를 사용할 수도 있지만 np.add처럼 범용함수를 사용할 수도 있다.
print(a1 + 1)
print(np.add(a1, 1))

print(a1 - 2)
print(np.subtract(a1,2))

print(-a1)
print(np.negative(a1))

print(a1 * 2)
print(np.multiply(a1,2))

print(a1 / 2)
print(np.divide(a1, 2))

print(a1 // 2)
print(np.floor_divide(a1, 2))

print(a1 ** 2)
print(np.power(a1, 2))

print(a1 % 2)
print(np.mod(a1, 2))

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[ 2  3  4  5  6  7  8  9 10]
[-1  0  1  2  3  4  5  6  7]
[-1  0  1  2  3  4  5  6  7]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


In [211]:
a1 = np.arange(1,10)
print(a1)
b1 = np.random.randint(1,10,size=9)
print(b1)

# 배열간 연산 가능
print(a1 + b1)
print(a1 - b1)
print(a1 * b1)
print(a1 / b1)
print(a1 // b1)
print(a1 ** b1)
print(a1 % b1)

[1 2 3 4 5 6 7 8 9]
[3 3 7 3 7 3 9 6 8]
[ 4  5 10  7 12  9 16 14 17]
[-2 -1 -4  1 -2  3 -2  2  1]
[ 3  6 21 12 35 18 63 48 72]
[0.33333333 0.66666667 0.42857143 1.33333333 0.71428571 2.
 0.77777778 1.33333333 1.125     ]
[0 0 0 1 0 2 0 1 1]
[       1        8     2187       64    78125      216 40353607   262144
 43046721]
[1 2 3 1 5 0 7 2 1]


In [212]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.random.randint(1,10,size=(3,3))
print(b2)

# 다차원 배열 사이에서도 연산 가능
print(a2 + b2)
print(a2 - b2)
print(a2 * b2)
print(a2 / b2)
print(a2 // b2)
print(a2 ** b2)
print(a2 % b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 3 3]
 [6 9 2]
 [1 6 6]]
[[10  5  6]
 [10 14  8]
 [ 8 14 15]]
[[-8 -1  0]
 [-2 -4  4]
 [ 6  2  3]]
[[ 9  6  9]
 [24 45 12]
 [ 7 48 54]]
[[0.11111111 0.66666667 1.        ]
 [0.66666667 0.55555556 3.        ]
 [7.         1.33333333 1.5       ]]
[[0 0 1]
 [0 0 3]
 [7 1 1]]
[[      1       8      27]
 [   4096 1953125      36]
 [      7  262144  531441]]
[[1 2 0]
 [4 5 0]
 [0 2 3]]


#### 절대값 함수(Absolute Function)

* `absolute()`, `abs()`: 내장된 절대값 함수

In [214]:
a1 = np.random.randint(-10,10,size=5)
print(a1)

print(np.absolute(a1))
print(np.abs(a1))

[ 4 -9 -1  5 -4]
[4 9 1 5 4]
[4 9 1 5 4]


#### 제곱/제곱근 함수

* `square`, `sqrt`: 제곱, 제곱근 함수

In [215]:
print(a1)
print(np.square(a1))
print(np.sqrt(a1))

[ 4 -9 -1  5 -4]
[16 81  1 25 16]
[2.                nan        nan 2.23606798        nan]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


#### 지수와 로그 함수 (Exponential and Log Function)

In [217]:
a1 = np.random.randint(1,10,size=5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1,2))

[2 5 9 6 6]
[7.38905610e+00 1.48413159e+02 8.10308393e+03 4.03428793e+02
 4.03428793e+02]
[  4.  32. 512.  64.  64.]
[ 4 25 81 36 36]


In [219]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[2 5 9 6 6]
[0.69314718 1.60943791 2.19722458 1.79175947 1.79175947]
[1.         2.32192809 3.169925   2.5849625  2.5849625 ]
[0.30103    0.69897    0.95424251 0.77815125 0.77815125]


#### 삼각 함수(Trigonometrical Function)


In [220]:
t = np.linspace(0,np.pi,3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [221]:
x = [-1,0,1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


### 집계 함수(Aggregate Functions)
* 집계함수는 숫자만 할 수 있는데 숫자가 아닌 어떤 값이 떴을 때는 에러를 리턴시킨다. NaN안전모드 함수를 사용하면 에러를 리턴하는게 아니라 안전하게 수행되도록 할 수 있다.

#### sum(): 합 계산


In [223]:
a2 = np.random.randint(1,10,size=(3,3))
print(a2)

print(a2.sum(), np.sum(a2))

#축을 기준으로 합하기
print(a2.sum(axis=0), np.sum(a2, axis=0))
print(a2.sum(axis=1), np.sum(a2,axis=1))

[[4 3 7]
 [4 2 8]
 [7 8 2]]
45 45
[15 13 17] [15 13 17]
[14 14 17] [14 14 17]


#### cumsum(): 누적합 계산

In [225]:
a2 = np.random.randint(1,10,size=(3,3))
print(a2)

print(np.cumsum(a2))

#축을 기준으로 누적합하기
print(np.cumsum(a2, axis=0))
print(np.cumsum(a2,axis=1))

[[3 1 7]
 [1 8 8]
 [1 1 7]]
[ 3  4 11 12 20 28 29 30 37]
[[ 3  1  7]
 [ 4  9 15]
 [ 5 10 22]]
[[ 3  4 11]
 [ 1  9 17]
 [ 1  2  9]]


#### diff(): 차분 계산

In [227]:
a2 = np.random.randint(1,10,size=(3,3))
print(a2)

print(np.diff(a2))

#축을 기준으로 차분 계산
print(np.diff(a2, axis=0))
print(np.diff(a2,axis=1))

[[8 9 7]
 [6 3 2]
 [2 5 3]]
[[ 1 -2]
 [-3 -1]
 [ 3 -2]]
[[-2 -6 -5]
 [-4  2  1]]
[[ 1 -2]
 [-3 -1]
 [ 3 -2]]


#### prod(): 곱 계산

In [228]:
a2 = np.random.randint(1,10,size=(3,3))
print(a2)

print(np.prod(a2))

#축을 기준으로
print(np.prod(a2, axis=0))
print(np.prod(a2,axis=1))

[[6 8 6]
 [1 2 9]
 [1 8 1]]
41472
[  6 128  54]
[288  18   8]


#### cumprod(): 누적곱 계산

In [229]:
a2 = np.random.randint(1,10,size=(3,3))
print(a2)

print(np.cumprod(a2))

#축을 기준으로
print(np.cumprod(a2, axis=0))
print(np.cumprod(a2,axis=1))

[[9 9 5]
 [1 5 2]
 [4 5 4]]
[     9     81    405    405   2025   4050  16200  81000 324000]
[[  9   9   5]
 [  9  45  10]
 [ 36 225  40]]
[[  9  81 405]
 [  1   5  10]
 [  4  20  80]]


#### dot()/matmul(): 점곱/행렬곱 계산

In [230]:
a2 = np.random.randint(1,10,size=(3,3))
print(a2)

b2 = np.ones_like(a2)
print(b2)

print(np.dot(a2,b2))
print(np.matmul(a2,b2))

[[7 8 5]
 [1 3 3]
 [7 4 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[20 20 20]
 [ 7  7  7]
 [20 20 20]]
[[20 20 20]
 [ 7  7  7]
 [20 20 20]]


#### tensordot(): 텐서곱 계산

In [231]:
print(a2)
print(b2)

print(np.tensordot(a2,b2))
print(np.tensordot(a2,b2,axes=0))
print(np.tensordot(a2,b2,axes=1))

[[7 8 5]
 [1 3 3]
 [7 4 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
47
[[[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]]


 [[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]]


 [[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[4 4 4]
   [4 4 4]
   [4 4 4]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]]]
[[20 20 20]
 [ 7  7  7]
 [20 20 20]]


#### cross(): 벡터곱

In [233]:
x = [1,2,3]
y = [4,5,6]
print(np.cross(x,y))

[-3  6 -3]


#### inner()/outer(): 내적/외적

In [234]:
print(a2)
print(b2)
print(np.inner(a2,b2))
print(np.outer(a2,b2))

[[7 8 5]
 [1 3 3]
 [7 4 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[20 20 20]
 [ 7  7  7]
 [20 20 20]]
[[7 7 7 7 7 7 7 7 7]
 [8 8 8 8 8 8 8 8 8]
 [5 5 5 5 5 5 5 5 5]
 [1 1 1 1 1 1 1 1 1]
 [3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3]
 [7 7 7 7 7 7 7 7 7]
 [4 4 4 4 4 4 4 4 4]
 [9 9 9 9 9 9 9 9 9]]


#### mean(): 평균 계산

In [236]:
print(a2)
print(np.mean(a2))
print(np.mean((a2), axis=0))
print(np.mean((a2), axis=1))

[[7 8 5]
 [1 3 3]
 [7 4 9]]
5.222222222222222
[5.         5.         5.66666667]
[6.66666667 2.33333333 6.66666667]


#### std(): 표준 편차 계산

In [237]:
print(a2)
print(np.std(a2))
print(np.std((a2), axis=0))
print(np.std((a2), axis=1))

[[7 8 5]
 [1 3 3]
 [7 4 9]]
2.528845928164676
[2.82842712 2.1602469  2.49443826]
[1.24721913 0.94280904 2.05480467]


#### var(): 분산 계산

In [238]:
print(a2)
print(np.var(a2))
print(np.var((a2), axis=0))
print(np.var((a2), axis=1))

[[7 8 5]
 [1 3 3]
 [7 4 9]]
6.395061728395062
[8.         4.66666667 6.22222222]
[1.55555556 0.88888889 4.22222222]


#### min(): 최소값

In [239]:
print(a2)
print(np.min(a2))
print(np.min((a2), axis=0))
print(np.min((a2), axis=1))

[[7 8 5]
 [1 3 3]
 [7 4 9]]
1
[1 3 3]
[5 1 4]


#### max(): 최대값

In [240]:
print(a2)
print(np.max(a2))
print(np.max((a2), axis=0))
print(np.max((a2), axis=1))

[[7 8 5]
 [1 3 3]
 [7 4 9]]
9
[7 8 9]
[8 3 9]


#### argmin(): 최소값 인덱스

In [243]:
# 최소값의 인덱스를 구한다
print(a2)
print(np.argmin(a2))
print(np.argmin((a2), axis=0))
print(np.argmin((a2), axis=1))

[[7 8 5]
 [1 3 3]
 [7 4 9]]
3
[1 1 1]
[2 0 1]


#### argmax(): 최대값 인덱스

In [244]:
# 최대값의 인덱스를 구한다
print(a2)
print(np.argmax(a2))
print(np.argmax((a2), axis=0))
print(np.argmax((a2), axis=1))

[[7 8 5]
 [1 3 3]
 [7 4 9]]
8
[0 0 2]
[1 1 2]


#### median(): 중앙값

In [245]:
print(a2)
print(np.median(a2))
print(np.median((a2), axis=0))
print(np.median((a2), axis=1))

[[7 8 5]
 [1 3 3]
 [7 4 9]]
5.0
[7. 4. 5.]
[7. 3. 7.]


#### percentile(): 백분위 수



In [247]:
a1 = np.array([0,1,2,3])
print(a1)
print(np.percentile(a1,[0,20,40,60,80,100], interpolation='linear'))
print(np.percentile(a1,[0,20,40,60,80,100], interpolation='higher'))
print(np.percentile(a1,[0,20,40,60,80,100], interpolation='lower'))
print(np.percentile(a1,[0,20,40,60,80,100], interpolation='nearest'))
print(np.percentile(a1,[0,20,40,60,80,100], interpolation='midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


#### any()

In [248]:
# 하나라도 True면 True
a2 = np.array([[False, False, False],
               [False, True, True],
               [False, True, True]])

print(a2)
print(np.any(a2))
print(np.any(a2, axis=0))
print(np.any(a2, axis=1))

[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


#### all()

In [250]:
#모두 True여야 True
a2 = np.array([[False, False, True],
               [True, True, True],
               [False, True, True]])

print(a2)
print(np.all(a2))
print(np.all(a2, axis=0))
print(np.all(a2, axis=1))

[[False False  True]
 [ True  True  True]
 [False  True  True]]
False
[False False  True]
[False  True False]


### 비교 연산(Comparison Operators)


In [252]:
# 연산자, 범용함수 둘 다 제공
a1 = np.arange(1,10)
print(a1)

print(a1 == 5) # 브로드캐스팅 지원
print(a1 != 5)
print(a1 < 5)
print(a1 <= 5)
print(a1 > 5)
print(a1 >= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]


In [259]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
print(np.sum(a2))

print(np.count_nonzero(a2 > 5)) # 5보다 큰 요소의 갯수

# 집계 함수에도 응용가능
print(np.sum(a2 > 5)) # 5보다 큰 요소의 갯수
print(np.sum(a2 > 5, axis=0))
print(np.sum(a2 > 5, axis=1))

print(np.any(a2 > 5)) # 하나라도 5보다 크면 True
print(np.any(a2 > 5, axis=0))
print(np.any(a2 > 5, axis=1))

print(np.all(a2 > 5)) # 모두 5보다 크면 True
print(np.all(a2 > 5, axis=0))
print(np.all(a2 > 5, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[1 1 2]
[0 1 3]
True
[ True  True  True]
[False  True  True]
False
[False False False]
[False False  True]


In [261]:
# 비교 범용 함수
a1 = np.array([1,2,3,4,5])
print(a1)
b1 = np.array([1,2,3,3,4])
print(b1)

print(np.isclose(a1,b1)) # 가까이에 있는지

[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [266]:
a1 = np.array([np.nan, 2, np.inf, 4, np.NINF])
print(a1)

print(np.isnan(a1)) # not a number인지
print(np.isinf(a1)) # 배열이 inf면 True
print(np.isfinite(a1)) # 배열이 inf, nan이면 False, 아니면 True

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


#### 불리언 연산자(Boolean Operators)


In [272]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)

print((a2 > 5) & (a2 < 8)) # and
print(a2[(a2 > 5) & (a2 < 8)]) # 불리언 인덱싱

print((a2 > 5) | (a2 < 8)) # or
print(a2[(a2 > 5) | (a2 < 8)]) # 불리언 인덱싱

print((a2 > 5) ^ (a2 < 8)) # xor
print(a2[(a2 > 5) ^ (a2 < 8)]) # 불리언 인덱싱

print(~(a2 > 5)) # not
print(a2[~(a2 > 5)]) # 불리언 인덱싱

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


### 배열 정렬

In [276]:
a1 = np.random.randint(1,10,size=10)
print(a1)

print(np.sort(a1))
print(np.argsort(a1)) # arg가 붙으면 index 출력임

print(a1)
a1.sort() # 정렬을 바로 적용하려면 a1.sort()
print(a1)

[1 1 1 6 6 2 3 3 7 5]
[1 1 1 2 3 3 5 6 6 7]
[0 1 2 5 6 7 9 3 4 8]
[1 1 1 6 6 2 3 3 7 5]
[1 1 1 2 3 3 5 6 6 7]


In [277]:
a2 = np.random.randint(1,10,size=(3,3))
print(a2)

print(np.sort(a2, axis=0))
print(np.sort(a2, axis=1))

[[6 1 2]
 [6 5 2]
 [3 3 9]]
[[3 1 2]
 [6 3 2]
 [6 5 9]]
[[1 2 6]
 [2 5 6]
 [3 3 9]]


#### 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

In [279]:
a1 = np.random.randint(1,10,size=10)
print(a1)
print(np.partition(a1,3))

[9 3 4 3 7 5 8 6 8 9]
[3 3 4 5 6 7 8 8 9 9]


In [281]:
a2 = np.random.randint(1,10,size=(5,5))
print(a2)
print(np.partition(a2,3))
print(np.partition(a2,3,axis=0))
print(np.partition(a2,3,axis=1))

[[9 9 1 7 8]
 [6 9 7 7 1]
 [7 9 8 5 8]
 [7 3 2 3 6]
 [7 1 5 1 5]]
[[7 1 8 9 9]
 [1 6 7 7 9]
 [5 7 8 8 9]
 [3 2 3 6 7]
 [1 5 1 5 7]]
[[6 3 2 3 6]
 [7 1 1 1 5]
 [7 9 5 5 1]
 [7 9 7 7 8]
 [9 9 8 7 8]]
[[7 1 8 9 9]
 [1 6 7 7 9]
 [5 7 8 8 9]
 [3 2 3 6 7]
 [1 5 1 5 7]]


## 배열 입출력
* 배열을 파일로 저장할 수 있음


In [282]:
a2 = np.random.randint(1,10,size=(5,5))
print(a2)

np.save("a", a2) # a라는 이름으로 파일을 저장

[[1 7 2 1 8]
 [5 3 4 6 4]
 [5 7 1 3 9]
 [7 2 6 6 9]
 [5 3 6 6 5]]


In [283]:
!ls # a.npy라는 바이너리 파일이 저장되었음을 확인할 수 있음

a.npy  sample_data


In [284]:
b2 = np.random.randint(1,10,size=(5,5))
print(b2)

np.savez("ab", a2,b2) # 2개의 배열을 하나의 파일로 저장

[[9 2 1 8 2]
 [7 6 6 5 6]
 [9 6 6 5 7]
 [7 4 8 6 8]
 [1 6 9 3 4]]


In [285]:
!ls

ab.npz	a.npy  sample_data


In [286]:
npy = np.load("a.npy") # 파일을 불러와줘
print(npy)

[[1 7 2 1 8]
 [5 3 4 6 4]
 [5 7 1 3 9]
 [7 2 6 6 9]
 [5 3 6 6 5]]


In [288]:
npz = np.load("ab.npz")
print(npz.files)

print(npz['arr_0'])
print(npz['arr_1'])

['arr_0', 'arr_1']
[[1 7 2 1 8]
 [5 3 4 6 4]
 [5 7 1 3 9]
 [7 2 6 6 9]
 [5 3 6 6 5]]
[[9 2 1 8 2]
 [7 6 6 5 6]
 [9 6 6 5 7]
 [7 4 8 6 8]
 [1 6 9 3 4]]


In [289]:
print(a2)

#바이너리 파일이 아니라 텍스트로 저장하고 싶다면
np.savetxt("a.csv", a2, delimiter=',') # 사람이 읽을 수 있는 여러 파일 단위 중 csv 사용

[[1 7 2 1 8]
 [5 3 4 6 4]
 [5 7 1 3 9]
 [7 2 6 6 9]
 [5 3 6 6 5]]


In [290]:
!ls

ab.npz	a.csv  a.npy  sample_data


In [291]:
!cat a.csv

1.000000000000000000e+00,7.000000000000000000e+00,2.000000000000000000e+00,1.000000000000000000e+00,8.000000000000000000e+00
5.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00,6.000000000000000000e+00,4.000000000000000000e+00
5.000000000000000000e+00,7.000000000000000000e+00,1.000000000000000000e+00,3.000000000000000000e+00,9.000000000000000000e+00
7.000000000000000000e+00,2.000000000000000000e+00,6.000000000000000000e+00,6.000000000000000000e+00,9.000000000000000000e+00
5.000000000000000000e+00,3.000000000000000000e+00,6.000000000000000000e+00,6.000000000000000000e+00,5.000000000000000000e+00


In [292]:
csv = np.loadtxt("a.csv", delimiter=',') # 저장, 불러올 때 구분자 delimiter 주의
print(csv)

[[1. 7. 2. 1. 8.]
 [5. 3. 4. 6. 4.]
 [5. 7. 1. 3. 9.]
 [7. 2. 6. 6. 9.]
 [5. 3. 6. 6. 5.]]


In [293]:
print(b2)
np.savetxt("b.csv", b2, delimiter=',', fmt='%.2e', header='c1,c2,c3,c4,c5') # format형태는 소숫점 2자리까지만, header는 c1,c..c5로 지정

[[9 2 1 8 2]
 [7 6 6 5 6]
 [9 6 6 5 7]
 [7 4 8 6 8]
 [1 6 9 3 4]]


In [295]:
!cat b.csv

# c1,c2,c3,c4,c5
9.00e+00,2.00e+00,1.00e+00,8.00e+00,2.00e+00
7.00e+00,6.00e+00,6.00e+00,5.00e+00,6.00e+00
9.00e+00,6.00e+00,6.00e+00,5.00e+00,7.00e+00
7.00e+00,4.00e+00,8.00e+00,6.00e+00,8.00e+00
1.00e+00,6.00e+00,9.00e+00,3.00e+00,4.00e+00


In [296]:
csv = np.loadtxt("b.csv", delimiter=',')
print(csv)

[[9. 2. 1. 8. 2.]
 [7. 6. 6. 5. 6.]
 [9. 6. 6. 5. 7.]
 [7. 4. 8. 6. 8.]
 [1. 6. 9. 3. 4.]]




---

